webtalk_init -webtalk_dir C:\\Users\\emink\\Desktop\\ekose\\LED_controller\\LED_controller.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Çar Þub 24 22:49:59 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "sifeg15l2lf0hkhcu3buqovvq7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1456343481723" -context "sdk\\\\hardware/1456343481723"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1456343481723"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1456343481723"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4" -context "sdk\\\\hardware/1456343481723"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1456343481723"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1456343481723"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1456343481723"
webtalk_add_data -client sdk -key uid -value "1456343698040" -context "sdk\\\\hardware/1456343698040"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1456343698040"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1456343698040"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4" -context "sdk\\\\hardware/1456343698040"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1456343698040"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1456343698040"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1456343698040"
webtalk_add_data -client sdk -key uid -value "1456343711904" -context "sdk\\\\bsp/1456343711904"
webtalk_add_data -client sdk -key hwid -value "1456343698040" -context "sdk\\\\bsp/1456343711904"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1456343711904"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1456343711904"
webtalk_add_data -client sdk -key uid -value "1456343811173" -context "sdk\\\\application/1456343811173"
webtalk_add_data -client sdk -key hwid -value "1456343698040" -context "sdk\\\\application/1456343811173"
webtalk_add_data -client sdk -key bspid -value "1456343711904" -context "sdk\\\\application/1456343811173"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1456343811173"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1456343811173"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1456343811173"
webtalk_transmit -clientid 1680973383 -regid "" -xml C:\\Users\\emink\\Desktop\\ekose\\LED_controller\\LED_controller.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\emink\\Desktop\\ekose\\LED_controller\\LED_controller.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\emink\\Desktop\\ekose\\LED_controller\\LED_controller.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
